In [1]:
import numpy as np

In [2]:
x=np.array([[1,2,3],[4,5,6]])

In [17]:
np.sum(x , axis=0)

array([5, 7, 9])

In [4]:
len(x.shape)

2

In [15]:
x = np.array([[1 ,2 ,3] , [4 ,5, 6]])
x.reshape(-1,1)#-1 simply represents unknown axis , numpy need to figure out itself .

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
np.max(x , axis=1)#axis =1 goes along side the x axis

array([3, 6])

In [ ]:
def softmax(x):
    """Compute the softmax function for each row of the input x.

    It is crucial that this function is optimized for speed because
    it will be used frequently in later code. You might find numpy
    functions np.exp, np.sum, np.reshape, np.max, and numpy
    broadcasting useful for this task.

    Numpy broadcasting documentation:
    http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

    You should also make sure that your code works for a single
    D-dimensional vector (treat the vector as a single row) and
    for N x D matrices. This may be useful for testing later. Also,
    make sure that the dimensions of the output match the input.

    You must implement the optimization in problem 1(a) of the
    written assignment!

    Arguments:
    x -- A D dimensional vector or N x D dimensional numpy matrix.

    Return:
    x -- You are allowed to modify x in-place
    """
    orig_shape = x.shape

    if len(x.shape) > 1:
        # Matrix
        ### YOUR CODE HERE
        
        ### END YOUR CODE
    else:
        # Vector
        ### YOUR CODE HERE
        raise NotImplementedError
        ### END YOUR CODE

    assert x.shape == orig_shape
    return x

In [1]:
import numpy as np


def sigmoid(x):
    """
    Compute the sigmoid function for the input here.

    Arguments:
    x -- A scalar or numpy array.

    Return:
    s -- sigmoid(x)
    """

    ### YOUR CODE HERE
    s=1/(1+np.exp(-x))
    
    
    
    
    ### END YOUR CODE

    return s


def sigmoid_grad(s):
    """
    Compute the gradient for the sigmoid function here. Note that
    for this implementation, the input s should be the sigmoid
    function value of your original input x.

    Arguments:
    s -- A scalar or numpy array.

    Return:
    ds -- Your computed gradient.
    """

    ### YOUR CODE HERE
    
    ds=sigmoid(s)*(1-sigmoid(s))
    
    ### END YOUR CODE

    return ds


def test_sigmoid_basic():
    """
    Some simple tests to get you started.
    Warning: these are not exhaustive.
    """
    print "Running basic tests..."
    x = np.array([[1, 2], [-1, -2]])
    f = sigmoid(x)
    g = sigmoid_grad(f)
    print f
    f_ans = np.array([
        [0.73105858, 0.88079708],
        [0.26894142, 0.11920292]])
    assert np.allclose(f, f_ans, rtol=1e-05, atol=1e-06)
    print g
    g_ans = np.array([
        [0.19661193, 0.10499359],
        [0.19661193, 0.10499359]])
    assert np.allclose(g, g_ans, rtol=1e-05, atol=1e-06)
    print "You should verify these results by hand!\n"


def test_sigmoid():
    """
    Use this space to test your sigmoid implementation by running:
        python q2_sigmoid.py
    This function will not be called by the autograder, nor will
    your tests be graded.
    """
    print "Running your tests..."
    ### YOUR CODE HERE
    raise NotImplementedError
    ### END YOUR CODE


if __name__ == "__main__":
    test_sigmoid_basic();
    test_sigmoid()

Running basic tests...


TypeError: 'numpy.ndarray' object is not callable

In [4]:
Dx=3
H=5
Dy=5
ofs=0
parameters=np.array([1 ,2 ,3 ,4,5,6,7,8,9])

In [2]:
import numpy as np

In [7]:
W1 = np.reshape(parameters[ofs:ofs+ 9], (3, 3))

In [8]:
W1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
w2=np.array([[1,2,3] , [4,5,6],[7,8,9]])

In [10]:
w2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.dot(W1,w2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [3]:
import numpy as np
a = np.array([[1 ,2, 3] , [3 ,4,5 ]])
b = np.array([[1 , 2, 3] , [3 , 4, 5]])
c = a*b
c

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [16]:
import numpy as np
import random

from q1_softmax import softmax
from q2_sigmoid import sigmoid, sigmoid_grad
from q2_gradcheck import gradcheck_naive


def forward_backward_prop(data, labels, params, dimensions):
    """
    Forward and backward propagation for a two-layer sigmoidal network
    Compute the forward propagation and for the cross entropy cost,
    and backward propagation for the gradients for all parameters.
    Arguments:
    data -- M x Dx matrix, where each row is a training example.
    labels -- M x Dy matrix, where each row is a one-hot vector.
    params -- Model parameters, these are unpacked for you.
    dimensions -- A tuple of input dimension, number of hidden units
                  and output dimension
    """

    ### Unpack network parameters (do not modify)
    ofs = 0
    Dx, H, Dy = (dimensions[0], dimensions[1], dimensions[2])
    M, _ = data.shape
    W1 = np.reshape(params[ofs:ofs+ Dx * H], (Dx, H))
    ofs += Dx * H
    b1 = np.reshape(params[ofs:ofs + H], (1, H))
    ofs += H
    W2 = np.reshape(params[ofs:ofs + H * Dy], (H, Dy))
    ofs += H * Dy
    b2 = np.reshape(params[ofs:ofs + Dy], (1, Dy))

    ### YOUR CODE HERE: forward propagation
    z1 = np.dot(data, W1) + b1
    a1 = sigmoid(z1)
    scores = np.dot(a1, W2) + b2

    y_pred = softmax(scores)
    cost = -np.sum(labels * np.log(y_pred))

    # ### END YOUR CODE

    # ### YOUR CODE HERE: backward propagation
    dscores = y_pred - labels
    gradW2 = np.dot(a1.T, dscores)
    gradb2 = np.sum(dscores, axis=0)
    da1 = np.dot(dscores, W2.T)
    dz1 = sigmoid_grad(a1)*da1
    gradW1 = np.dot(data.T, dz1)
    gradb1 = np.sum(dz1, axis=0)

    ### END YOUR CODE

    ### Stack gradients (do not modify)
    grad = np.concatenate((gradW1.flatten(), gradb1.flatten(),
        gradW2.flatten(), gradb2.flatten()))

    return cost, grad


def sanity_check():
    """
    Set up fake data and parameters for the neural network, and test using
    gradcheck.
    """
    print "Running sanity check..."

    N = 20
    dimensions = [10, 5, 10]
    data = np.random.randn(N, dimensions[0])   # each row will be a datum
    labels = np.zeros((N, dimensions[2]))
    for i in xrange(N):
        labels[i, random.randint(0,dimensions[2]-1)] = 1

    params = np.random.randn((dimensions[0] + 1) * dimensions[1] + (
        dimensions[1] + 1) * dimensions[2], )

    gradcheck_naive(lambda params:
        forward_backward_prop(data, labels, params, dimensions), params)


def your_sanity_checks():
    """
    Use this space add any additional sanity checks by running:
        python q2_neural.py
    This function will not be called by the autograder, nor will
    your additional tests be graded.
    """
    print "Running your sanity checks..."
    ### YOUR CODE HERE
    raise NotImplementedError
    ### END YOUR CODE


if __name__ == "__main__":
    sanity_check()
    your_sanity_checks()

Running sanity check...


TypeError: 'numpy.ndarray' object is not callable